### ISSUE TITLE
Generators broken uglify

### ISSUE THREAD

**Issue by carlosvillu** [isaacs/yallist#14]
Hi, 

I am trying to minify this library with Uglifly, but I get this:
```
ERROR in app.21ccc9db4f755fbb49a3.js from UglifyJs
Unexpected token operator «*», expected punc «(» [../~/yallist/iterator.js:3,0][app.21ccc9db4f755fbb49a3.js:34654,45]
```

That is because Uglify don´t know how manage generator functions more info here: https://github.com/mishoo/UglifyJS2/issues/448

Can you transpile that function?!

**Comment by maxnowack** [comment]
I'm having the same issue. Please provide an update

**Comment by ivan-rudyi-personal** [comment]
+1

**Comment by HashDot** [comment]
+1

**Comment by isaacs** [comment]
Reverted in 2.1.1, re-added and published as 3.0.0.

Sorry for the hiccup!

**Comment by isaacs** [comment]
Just so I can help avoid this in the future, was the issue that a version of uglify is using this module, or that using this module in a project that uses uglify will cause it to break?  I had thought that putting the iterator stuff behind a `try { require(...) }` would keep the language feature from being a breaking change, but I guess that's not sufficient?

**Comment by QuentinFchx** [comment]
> using this module in a project that uses uglify will cause it to break

^ this
https://github.com/mishoo/UglifyJS2/issues/448
