### ISSUE TITLE
es5 support

### ISSUE THREAD

**Issue by inbaldoron** [isaacs/yallist#15]
Hi,
we have noticed that since iterator.js was introduced your package doesn't support es5 environment any more.
would it be possible to support it?

**Comment by turbidwater** [comment]
I will second this bug. We had some of our dependencies just move to a more recent version, and now it is breaking our UglifyJS

**Comment by isaacs** [comment]
I guess the try/catch doesn't avoid the error, then?  Can you please provide a reproduction case so I can debug directly?

**Comment by turbidwater** [comment]
It's happening during build time when uglify-js tries to parse the library code, so the try/catch won't block that. We have a typescript project that is compiling to es5. I'll see if I can throw together a sample with the minimum stuff.

**Comment by isaacs** [comment]
Well, there's really no way to make that work, then.  The iteration feature showed up in v3.0.0, as a breaking change.  You'll have to set your dependency to 2.x if you need to parse the code back to ES 5.
