### ISSUE TITLE
ISC license?

### ISSUE THREAD

**Issue by jdalton** [isaacs/yallist#16]
I noticed some of your [other](https://github.com/isaacs/minizlib/blob/666b33cf8158c12111046d94449eed53c9c9fab2/package.json#L30) related projects were MIT and wondered if it was an oversight here and [here](https://github.com/isaacs/minipass/blob/374dee67e86ca47b79573ed70a642ab20ae50853/package.json#L27). Or maybe that one is the odd one out. Either way I figured I'd ask.

**Comment by isaacs** [comment]
I default to ISC, but when forking or creating a derivative work of an MIT licensed project, it's more straightforward to use the same license.

Minizlib is derivative of code in node.js.  Minipass-fetch is a derivative work of node-fetch.  So those two are MIT-licensed, but everything else I do is usually ISC.
