### ISSUE TITLE
Insert into the middle of a list?

### ISSUE THREAD

**Issue by arosequist** [isaacs/yallist#17]
If I have a `Node`, is it possible to insert an item directly before or directly after it using this library?

The only existing functions I see for insertion are `unshift` (at the beginning of the list) and `push` (at the end of the list).

**Comment by isaacs** [comment]
I'd accept a pull request to add a `splice` function that works like the Array function by the same name.

**Comment by mo4islona** [comment]
Pull request is ready.

I`ve also removed old versions of node from travic-ci config to make tests green.

**Comment by martinheidegger** [comment]
This change also makes this library Node < 6 incompatible: (see #21) - this made this a breaking change, no? (semver-major)
