### ISSUE TITLE
Question about cycles

### ISSUE THREAD

**Issue by seansd** [isaacs/yallist#18]
There are many places in the code where it iterates from a node to the next/prev, one example:

https://github.com/isaacs/yallist/blob/master/yallist.js#L153-L155

```
   for (var walker = this.head, i = 0; walker !== null; i++) {
    fn.call(thisp, walker.value, i, this)
    walker = walker.next
   }
```

Shouldn't this do a check to see if `walker === walker.next` to prevent a never ending loop cycle?
And 2ndarily should it just break out? Or should it throw an error?

**Comment by isaacs** [comment]
I'm not sure how you'd ever end up with a cycle, unless you were manually changing the node links.  Do you have a reproduction case where this is possible?
