### ISSUE TITLE
Inline iterator code

### ISSUE THREAD

**Issue by domoritz** [isaacs/yallist#27]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `yallist@4.0.0` for the project I'm working on.

The issue I had was that many bundlers don't support require inside try-catch. It would be nice if you could inline the code instead. 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/yallist/yallist.js b/node_modules/yallist/yallist.js
index 4e83ab1..f25394e 100644
--- a/node_modules/yallist/yallist.js
+++ b/node_modules/yallist/yallist.js
@@ -422,5 +422,9 @@ function Node (value, prev, next, list) {
 
 try {
   // add if support for Symbol.iterator is present
-  require('./iterator.js')(Yallist)
+  Yallist.prototype[Symbol.iterator] = function* () {
+    for (let walker = this.head; walker; walker = walker.next) {
+      yield walker.value
+    }
+  }
 } catch (er) {}
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by lcoder** [comment]
hope merge these code
